---
title: "Resistance and Sensitivity Genes"
author: "Andrew Kavran"
output: html_document
---

```{r, message = FALSE, warning=FALSE}
library(DESeq2)
library(magrittr)
library(dplyr)
```

Load in preprocessed rna seq data image.
```{r}
load("../data/processed_rna_seq_data.rda")
source("./Helper_Functions/dend_sort_exp.R")
source("./Helper_Functions/plot_heatmap.R")
source("Helper_Functions/sort_exp.R")
```

```{r}
lfc_thresh = 0.97
a_thresh = 0.05
r56 = results(dds, contrast = c('condition', '5', '6'), alpha = a_thresh, lfcThreshold = lfc_thresh, altHypothesis = "greaterAbs")
r68 =  results(dds,contrast = c('condition', '6', '8'),  alpha=a_thresh, lfcThreshold = lfc_thresh, altHypothesis = "greaterAbs")
r108 =  results(dds,contrast = c('condition', '10', '8'),  alpha=a_thresh, lfcThreshold = lfc_thresh, altHypothesis = "greaterAbs")
```

Identify genes that meet reversibility criteria.
```{r}
meet_criteria = which(r56$padj<a_thresh & r68$padj<a_thresh & r108$padj<a_thresh & (sign(r68$log2FoldChange) == sign(r108$log2FoldChange)))
reversible_genes = gene_names$symbol[meet_criteria]
```

Load in resistance and sensitivity gene names and categories.
```{r}
rs_genes = read.csv("../data/resistance_sensitivity_genes.csv", stringsAsFactors = FALSE)
map = match(rs_genes$symbol, gene_names$symbol)
lfc = as.data.frame(rlog_data[map,] - rowMeans(rlog_data[map,c(1:3)]))
colnames(lfc) = c(rep("Vector", 3), rep("V600E", 3), rep("20hr Drug", 3), rep("Week 1 CONT", 3), rep("Week 2 CONT", 3), rep("Week 2 INT (OFF)", 3), rep("Week 3 CONT", 3), rep("Week 3 INT (ON)", 3), rep("Week 4 CONT", 2), rep("Week 4 INT (OFF)", 3))
lfc_data_frame = data.frame(gene_name = gene_names[map,], category = rs_genes$category, lfc)
```

Plot heatmaps
```{r}
index = 1
lfc_data_frame2 = data.frame()
categories = c("IC", "RS", "RR")
for (ii in categories) {
  sub_data = lfc_data_frame %>% filter(category == ii)
  rownames(sub_data) = sub_data$gene_name.symbol
  dist.mat = dist(sub_data[,8:33])
  hc = hclust(dist.mat, method = "ward.D2")
  mean_exp = round(rowMeans(sub_data[hc$order,c(20:22, 26:28, 31:33)]),4)
  hc2 = dend_sort_exp(hc, mean_exp) #sort the dendrogram
  
  sub_data = sub_data[hc2$order, ]
  lfc_data_frame2 = bind_rows(lfc_data_frame2, sub_data) #replace in lfc
  index = index+(index+dim(sub_data)[1])
}
lfc_only = lfc_data_frame2[-c(1:4)]
lfc_only = lfc_only[,c(1:15, 19:21,25,26,16:18,22:24,27:29)]
horz_breaks= c(25, 37)
plot_heatmap(lfc_only, thresh = 0.97, cluster_rows = FALSE, cluster_cols = FALSE, gaps_col = c(9,20), gaps_row = horz_breaks, legend_breaks = c(-6, -4, -2, -0.97, 0, 0.97, 2, 4, 6), labels_row = lfc_data_frame2$gene_name.symbol, show_colnames=FALSE, fontsize = 7)
dev.copy2eps(file="../results/Resistance_and_Sensitivity_Genes_Script_Output/Resistance_and_Sensitivity_Genes_Script_Output.eps")
```
Confirm that all the reversible resistance/sensitivity genes meet the above criteria.
```{r}
reversible_rs = !(match(rs_genes$symbol, reversible_genes) %>% is.na)
rs_genes$symbol[!(reversible_rs ==(rs_genes$category == "RR" |rs_genes$category == "RS"))]
```

```{r}
sub_data = lfc_data_frame %>% filter(category == "O")
rownames(sub_data) = sub_data$gene_name.symbol
dist.mat = dist(sub_data[,8:33])
hc = hclust(dist.mat, method = "ward.D2")
mean_exp = round(rowMeans(sub_data[hc$order,8:33]),4)
hc2 = dend_sort_exp(hc, mean_exp) #sort the dendrogram

lfc_other_only = sub_data[-c(1:4)]
lfc_other_only = lfc_other_only[,c(1:15, 19:21,25,26,16:18,22:24,27:29)]

plot_heatmap(lfc_other_only, thresh = 0.97, cluster_rows = hc2, cluster_cols = FALSE, gaps_col = c(9,20), legend_breaks = c(-6, -4, -2, -0.97, 0, 0.97, 2, 4, 6), labels_row = lfc_other_only$gene_name.symbol, show_colnames=FALSE, fontsize = 7)
dev.copy2eps(file="../results/Resistance_and_Sensitivity_Genes_Script_Output/Supplemental_Resistance_and_Sensitivity_Genes_Script_Output.eps")
```

